// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/add": {
            "post": {
                "description": "用于添加新用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块（管理员）"
                ],
                "summary": "添加用户",
                "parameters": [
                    {
                        "description": "注册请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app_api_v1.AddUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "/add/sign_in": {
            "post": {
                "description": "用于用户签到",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块（管理员）"
                ],
                "summary": "用户签到",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    }
                }
            }
        },
        "/delete": {
            "post": {
                "description": "用于删除用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块（管理员）"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "description": "注册请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app_api_v1.DeleteUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    }
                }
            }
        },
        "/get/login": {
            "post": {
                "description": "用于获取全局用户的登录状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "获取用户登录状态",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app_api_v1.GetLoginUserResponseData"
                        }
                    }
                }
            }
        },
        "/get/sign_in": {
            "get": {
                "description": "用于用户查看签到日历",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块（管理员）"
                ],
                "summary": "签到日历",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                }
            }
        },
        "/list/page": {
            "post": {
                "description": "用于获取所有用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块（管理员）"
                ],
                "summary": "用户列表",
                "parameters": [
                    {
                        "description": "注册请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app_api_v1.UserQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app_api_v1.UserQueryResponseData-app_api_v1_User"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "用于实现用户的登录功能",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "注册请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app_api_v1.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app_api_v1.LoginResponseData"
                        }
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "description": "用于实现用户的注销功能",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "用户注销",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "用于实现用户的注册功能",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app_api_v1.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app_api_v1.Response"
                        }
                    }
                }
            }
        },
        "/update": {
            "post": {
                "description": "用于修改用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块（管理员）"
                ],
                "summary": "修改用户",
                "parameters": [
                    {
                        "description": "注册请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app_api_v1.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app_api_v1.AddUserRequest": {
            "type": "object",
            "properties": {
                "userAccount": {
                    "type": "string"
                },
                "userAvatar": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                },
                "userProfile": {
                    "type": "string"
                },
                "userRole": {
                    "type": "string"
                }
            }
        },
        "app_api_v1.DeleteUserRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "app_api_v1.GetLoginUserResponseData": {
            "type": "object",
            "properties": {
                "createTime": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "updateTime": {
                    "type": "string"
                },
                "userAvatar": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                },
                "userProfile": {
                    "type": "string"
                },
                "userRole": {
                    "type": "string"
                }
            }
        },
        "app_api_v1.LoginRequest": {
            "type": "object",
            "required": [
                "userAccount",
                "userPassword"
            ],
            "properties": {
                "userAccount": {
                    "type": "string",
                    "example": "123456"
                },
                "userPassword": {
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "app_api_v1.LoginResponseData": {
            "type": "object",
            "properties": {
                "createTime": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "updateTime": {
                    "type": "string"
                },
                "userAvatar": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                },
                "userProfile": {
                    "type": "string"
                },
                "userRole": {
                    "type": "string"
                }
            }
        },
        "app_api_v1.RegisterRequest": {
            "type": "object",
            "required": [
                "checkPassword",
                "userAccount",
                "userPassword"
            ],
            "properties": {
                "checkPassword": {
                    "type": "string",
                    "example": "123456"
                },
                "userAccount": {
                    "type": "string",
                    "example": "1234456"
                },
                "userPassword": {
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "app_api_v1.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "app_api_v1.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "userAccount": {
                    "type": "string"
                },
                "userAvatar": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                },
                "userProfile": {
                    "type": "string"
                },
                "userRole": {
                    "type": "string"
                }
            }
        },
        "app_api_v1.User": {
            "type": "object",
            "properties": {
                "createTime": {
                    "type": "string"
                },
                "editTime": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isDelete": {
                    "type": "integer"
                },
                "mpOpenId": {
                    "type": "string"
                },
                "unionId": {
                    "type": "string"
                },
                "updateTime": {
                    "type": "string"
                },
                "userAccount": {
                    "type": "string"
                },
                "userAvatar": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                },
                "userPassword": {
                    "type": "string"
                },
                "userProfile": {
                    "type": "string"
                },
                "userRole": {
                    "type": "string"
                }
            }
        },
        "app_api_v1.UserQueryRequest": {
            "type": "object",
            "properties": {
                "current": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "mpOpenId": {
                    "type": "string"
                },
                "pageSize": {
                    "type": "integer"
                },
                "sortField": {
                    "type": "string"
                },
                "sortOrder": {
                    "type": "string"
                },
                "unionId": {
                    "type": "string"
                },
                "userAccount": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                },
                "userProfile": {
                    "type": "string"
                },
                "userRole": {
                    "type": "string"
                }
            }
        },
        "app_api_v1.UserQueryResponseData-app_api_v1_User": {
            "type": "object",
            "properties": {
                "current": {
                    "description": "当前页码",
                    "type": "integer"
                },
                "pages": {
                    "description": "总页数",
                    "type": "integer"
                },
                "records": {
                    "description": "当前页的记录列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/app_api_v1.User"
                    }
                },
                "size": {
                    "description": "每页大小",
                    "type": "integer"
                },
                "total": {
                    "description": "总记录数",
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8000",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Nunu Example API",
	Description:      "This is a sample server celler server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
